language: java
services:
- docker
before_script:
- unset _JAVA_OPTIONS
- cd finish
- chmod +x ../scripts/travisTest.sh
script: ../scripts/travisTest.sh
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: dHWdxGl7DBGJMPXKMvzkMfRNOm1FF9Tmfzzq+KZXY4qnYWZjXERTlhKo5qdAiL5jqupVCUoc3pAliqupUMJPekXnfb66dImxq9FV7hHfpq5rpArvjvcyzisZriKB6MN+dKNESHm+NK+fQ/Mpp9dzHsSDhrkiFW5bubv59s4V5wmIPHp0eQ8QAHnfegTo3UX/8wuNBudaUHMnD6KtJMBbDVa7oYo1EsFGaoERG/XqcGasK7c9T1kqUAM/CRpIvT5EflYqbLKrmRtCN1IsKhFpMhJ/SAC88t84BBOsDhrajneNbj4P+GH2EXr6zOLJzGwmZoziW8CKW+lBysH/VHb3fqtaMfUxW+4iPwF1OZJswT61TPeaykPuAW10pvrK7Ytz3Fr54TskpTE5JgiqL8W3AusNLbIO++Ot51jUT4hh8s8AzhLETBhXtUXqdaqNmVYCLw5EVVnKZWJKN3Nme9emI9gyB4/7Z4Q8UjwKKzDE5TUZiNN8F42wtb8qG+4PJtJOnCFzEP2AKFI0cRmuyUdZJ3VTQfqEv1PSMONo0Tkvp+DGeKwseJcWqsIYQ/UgTReo5KEok4Uo7IoRepPP2VwCpyrj6nF/l9TM/lSa3vnWMeJ9cnShfn/kuxA2Jf0ogk9KmzDKfQrG8e0oasmvKuSkO0asXa6xOw387dW1j0funvw=
    on_success: never
    on_failure: always
branches:
  only:
  - master
  - qa
